name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  kindletool:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: NiLuJe/KindleTool
    - name: Compile KindleTool
      run: |
          sudo apt-get install -y zlib1g-dev libarchive-dev nettle-dev
          make
    - uses: actions/upload-artifact@v4
      with:
        name: kindletool
        path: KindleTool/Release/kindletool
  build:
    runs-on: ubuntu-latest
    needs: kindletool

    steps:
    - uses: actions/checkout@v4
    - name: Remove old Kindletool
      run: rm -f ./utils/kindletool
    - uses: actions/download-artifact@v4
      with:
        name: kindletool
        path: ./utils/
    - name: build
      run: |
          chmod 755 ./utils/kindletool
          chown -R $USER: ./utils/
          sh ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: XMAS_JB
        path: build/*