name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: XMAS_JB
        path: build/XMAS_JB.tar.gz
